### ISSUE TITLE
[Update] Improvements to v2.0.0-beta-0.2

### ISSUE THREAD

**Issue by seohyunsim** [modern-agile-team/dev-portfolio#164]
## Description
> 라이브러리를 직접 적용해보며 추가된 개선사항을 수정한다.

### 폰트색상 props 추가
> 어두운색 배경을 지정할수도 있기에 폰트색상 props 필요.   
추가되거나 변경된 props 명은 PR을 통해 확인할 것.

  - [x] Intro : titleColor, shortIntroColor
     - #173
     - [x] Must update of **Intro** component in README.md
<img width="1719" alt="스크린샷 2022-10-03 오전 1 48 03" src="https://user-images.githubusercontent.com/56839474/193465972-13a75ef9-686c-4b44-a9f7-3e8c1324bc5f.png">

  - [x] TechStackList
     - #177 
     - [x] Must update of **TechStackList** component in README.md
<img width="1689" alt="스크린샷 2022-10-03 오후 4 02 37" src="https://user-images.githubusercontent.com/56839474/193518582-7906eb1e-0f28-41ce-887e-f60efa1a6e74.png">

  - [x] ProgressBar
     - #177 
     - [x] Must update of **ProgressBar** component in README.md
<img width="1696" alt="스크린샷 2022-10-03 오후 4 03 20" src="https://user-images.githubusercontent.com/56839474/193518693-b90cc147-d48e-4a32-b978-4838b254c43f.png">

  - [x] VisitorCounter : titleColor, todayTitleColor, totalTitleColor
  - [x] Contact: textColor, buttonBackgroundColor, buttonTextColor 
     - #173
     - [x] Must update of **Contact** component in README.md
<img width="1718" alt="스크린샷 2022-10-03 오전 1 56 16" src="https://user-images.githubusercontent.com/56839474/193466362-e2505b72-3054-409e-b750-8f0599711bea.png">

  - [x] VisitorComment
     - #180 
     - [x] Must update of **VisitorComment** component in README.md
<img width="1728" alt="스크린샷 2022-10-03 오후 6 31 29" src="https://user-images.githubusercontent.com/56839474/193545434-383cfd01-676a-4f16-9f2c-17bfaa37c136.png">

  - [x] Skill
     - #173
     - [x] Must update of **Skill** component in README.md
<img width="305" alt="스크린샷 2022-10-03 오전 2 21 27" src="https://user-images.githubusercontent.com/56839474/193467371-0d341d67-1006-4fd1-b55c-593c27a34c54.png">
<img width="177" alt="스크린샷 2022-10-03 오전 2 23 19" src="https://user-images.githubusercontent.com/56839474/193467444-94fc8b04-75ee-40c0-b116-647fb7a5adab.png">

  - [x] Item
     - #173
     - [x] Must update of **Item** component in README.md
<img width="453" alt="스크린샷 2022-10-03 오전 3 39 19" src="https://user-images.githubusercontent.com/56839474/193470488-b68061e5-6e93-489f-84c2-9d11d7d52704.png">

  - [x] Image
     - #173
     - [x] Must update of **Image** component in README.md
<img width="406" alt="스크린샷 2022-10-03 오전 5 02 09" src="https://user-images.githubusercontent.com/56839474/193473856-9a5f0fb4-a10b-4c85-b789-8edb7b51e2be.png">

### progressbar 게이지 올라가는 애니메이션 빼는 props 생성
> 있다면 VisitorComment에 있는progressbar애니메이션 빼야함 (wave 모션도 마찬가지)

- [x] animation work props

### teckStackList colorFrom props가 작동하지 않음
- [x] colorFrom props 수정

### Gallery hover시 아이템을 감싸는 색상을 변경할 수 있는 props추가
>  기존에 theme라는 프롭스로 이미 제공되고 있었음.
 - [x] done.
 - [x] Must update of **Galley's theme props** in README.md
 theme 설명을 조금 더 이해하기 쉽도록 변경했음. 리드미 수정해줘야함.
```ts
/**
 * @props theme: You can choose the color of your customized components in Gallery when they are hoverd with a variety of  theme such as 'mid-night', 'blossom', 'fruits', 'bare-bare', 'mint-chocolate'.	(default: mid-night)
 */
```
<img width="447" alt="스크린샷 2022-10-03 오전 3 53 53" src="https://user-images.githubusercontent.com/56839474/193471119-218d6adf-80fa-4545-b0b5-806816b4732d.png">

### Carousel 버그 수정
- [x] done

### 방명록 프로그레스바에 레이트 감추기 
  - [x] isHiddenRateText 트루로 설정
![image](https://user-images.githubusercontent.com/83394348/193845344-8034aece-380f-486e-88d9-866406ecc4ee.png)

### 방문자 계수기 디폴트테망 하단 패딩 체크하기
- [x] done
![image](https://user-images.githubusercontent.com/83394348/193845448-c9f993b3-209b-4bf1-9ddd-b6dbffc5ece4.png)

**Comment by woorim960** [comment]
@seohyunsim 
techStackList의 progressbar - colorFrom 정상 동작하는지 순기가 확인했는데 잘됨.
visitorComment의 progressbar인지 검토 필요.
