### ISSUE TITLE
[Feat] Questions and Necessities in the Teckstack Props

### ISSUE THREAD

**Issue by seohyunsim** [modern-agile-team/dev-portfolio#77]
## Description
> 기술스택 컴포넌트에서의 개선사항

## Progress
- [x] fontSize/logoSize props 적용 안된거 같음
- [x] iconColor Props 적용 안됨
- [x] progressBar 두께 조절할수 있는 props있었으면
- [x] logo name은 적을수 있게 하되 title값은 사용자가 작성할수 있게 했으면 / 아니면 name 값이 안보이게
ex)
- typescript는 아이콘 모양이 3개임
<img width="635" alt="image" src="https://user-images.githubusercontent.com/83394348/183034688-edc34465-067c-4743-99d1-5e712c56d8d8.png">

- 다른 아이콘 모양으로 하고싶었으나 name에 -icon까지 같이 보이게 됨
<img width="190" alt="image" src="https://user-images.githubusercontent.com/83394348/183034778-cb950067-8cd1-49d6-a392-732ce7c546c0.png">

**Comment by woorim960** [comment]
iconColor는 고정이라 삭제하였음.

**Comment by woorim960** [comment]
TechStack에서 name과 logoName을 구분하여 등록하도록 하였음.
