### ISSUE TITLE
[Feat] Questions and Necessities in the Gallery Props

### ISSUE THREAD

**Issue by seohyunsim** [modern-agile-team/dev-portfolio#81]
## Description
> Gallery 컴포넌트에서의 개선사항

## Progress
- [x] 열을 지정하는 props가 col로 되어있던데, column으로 변경해서 좀 더 명시적인 props명이였음 좋겠음
- [x] description에서 \n일때 줄바꿈 처리가 되었으면 좋겠음
- padding="0em 20em"일때 웹
![image](https://user-images.githubusercontent.com/83394348/183231407-1dc58718-a920-4217-a3ef-bce4f31103de.png)

- padding="0em 20em"일때 max-width 768px
![image](https://user-images.githubusercontent.com/83394348/183231429-fff5c94f-fe3b-48ce-9c2c-fb80b067e1dc.png)

**Comment by soonki-98** [comment]
반응형에서 padding 적용 안시키는건 안됨
그냥 유저가 자바스크립트로 padding값 넣어줘야함
