### ISSUE TITLE
[Feat] Questions and Necessities in the Contact Props 

### ISSUE THREAD

**Issue by seohyunsim** [modern-agile-team/dev-portfolio#82]
## Description
> Contact 컴포넌트에서의 개선사항

## Progress
- [x] 배경색(background-color) props가 있었으면 좋겠음
- [x] aboutMeInfos props의 타입이 Object로 선언되어있던데, 좀 더 명시적인 타입이였으면

**Comment by woorim960** [comment]
## <Type 선언 원칙>
* 컴포넌트에 사용되는 모든 Type은 '컴포넌트+Type.ts' 한 파일에서 관리하고, Interface로 선언한다.
* Type 키워드는 Enum 타입을 만들 때만 사용.  
<img width="1013" alt="type 선언 원칙" src="https://user-images.githubusercontent.com/56839474/183922605-e92251af-144f-4369-84cf-418a75aa8595.png">
